version: '3.4'

services:
  bds:
    container_name: mcbds
    image: itzg/minecraft-bedrock-server
    user: 998:998
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "GAME NIGHT NEVER STOPS!"
    network_mode: "host"
    volumes:
      - /opt/minecraft/data:/data
    stdin_open: true
    tty: true
    restart: always
